<?php
include("process/header.php");

include("process/connect.php");
$queries = array(
"INSERT INTO `roomdetail` VALUES ('1', NULL, 'ธรรมดา', NULL, NULL, '2,700 บาท', '40');",
"INSERT INTO `roomdetail` VALUES ('10', NULL, NULL, 'เตียง ฟูก ระเบียง เฟอร์นิเจอร์ เครื่องทำน้ำอุ่น', 'ห้องสูทคู่(สองห้องคู่)', '12,000 บาท', '14');",
"INSERT INTO `roomdetail` VALUES ('100', NULL, 'แอร์', 'เตียง ฟูก พัดลม ระเบียง โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น ตู้เย็น ทีวี', NULL, '4,500 บาท', '86');",
"INSERT INTO `roomdetail` VALUES ('101', NULL, NULL, 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '2600 บาท', '136');",
"INSERT INTO `roomdetail` VALUES ('102', '3.5 x 4.5 ตร.ม.', NULL, 'เตียง ระเบียง ตู้เสื้อผ้า พัดลม', NULL, '2,500 บาท', '134');",
"INSERT INTO `roomdetail` VALUES ('103', '3.5 x 4.5 ตร.ม.', 'แอร์', 'เตียง ระเบียง ตู้เสื้อผ้า พัดลม', NULL, '3,200 บาท', '134');",
"INSERT INTO `roomdetail` VALUES ('104', '3.4 x 4.0 ตร.ม.', NULL, 'เตียง ระเบียง พัดลม', NULL, '2,500 บาท', '135');",
"INSERT INTO `roomdetail` VALUES ('105', '4.0 x 4.0 ตร.ม.', NULL, 'เตียง ระเบียง พัดลม', NULL, '2,800 บาท', '135');",
"INSERT INTO `roomdetail` VALUES ('106', '4.0 x 4.75 ตร.ม.', NULL, 'เตียง ระเบียง พัดลม', NULL, '3,000 บาท', '135');",
"INSERT INTO `roomdetail` VALUES ('107', '3x6 ตร.ม.', 'แอร์', 'เตียง ฟูก ระเบียง ราวตาก โต๊ะ ตู้', NULL, '4,000 บาท', '107');",
"INSERT INTO `roomdetail` VALUES ('108', NULL, 'แอร์', 'เตียง ฟูก  ราวตาก โต๊ะ ตู้', 'อยู่ชั้น 1 ไม่มีระเบียง', '3,500 บาท', '107');",
"INSERT INTO `roomdetail` VALUES ('109', NULL, 'พัดลม', 'เตียง ฟูก ระเบียง โต๊ะคอม ตู้เสื้อผ้า พัดลม', NULL, '3,000 บาท', '95');",
"INSERT INTO `roomdetail` VALUES ('11', '20 ตร.ม.', 'แอร์', 'เตียง,ฟูก,ตู้เสื้อผ้า,โต๊ะ,มีชั้นวาง,โต๊ะคอม,เก้าอี้มี 2 ชุด', 'อยู่ได้ 2 คน,ชั้นบนสุด', '4,800 บาท', '1');",
"INSERT INTO `roomdetail` VALUES ('110', NULL, 'แอร์', 'เตียง ฟูก ระเบียง โต๊ะคอม ตู้เสื้อผ้า แอร์', NULL, '4,000 บาท', '95');",
"INSERT INTO `roomdetail` VALUES ('111', '3x7 ตร.ม.', 'พัดลม', 'ระเบียง โต๊ะญี่ปุ่น ตู้เสื้อผ้า', NULL, '2,700 บาท', '97');",
"INSERT INTO `roomdetail` VALUES ('112', '3x7 ตร.ม.', 'แอร์', 'ระเบียง โต๊ะญี่ปุ่น ตู้เสื้อผ้า', NULL, '3,000 บาท', '97');",
"INSERT INTO `roomdetail` VALUES ('113', '4 x 3.5 ตร.ม.', 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '2,700 บาท', '98');",
"INSERT INTO `roomdetail` VALUES ('114', '4 x 3.5 ตร.ม.', 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,200 บาท', '98');",
"INSERT INTO `roomdetail` VALUES ('115', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', 'ห้องมุมจ่ายเพิ่ม 500 บาท', '3,000 บาท', '101');",
"INSERT INTO `roomdetail` VALUES ('116', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', 'ห้องมุมจ่ายเพิ่ม 500 บาท', '4,000 บาท', '101');",
"INSERT INTO `roomdetail` VALUES ('117', NULL, 'พัดลม', 'เตียง ฟูก ระเบียง พัดลม', NULL, '2,700 บาท', '99');",
"INSERT INTO `roomdetail` VALUES ('118', NULL, 'พัดลม', 'เตียง ระเบียง โต๊ะคอม ตู้เสื้อผ้า พัดลม', NULL, '', '100');",
"INSERT INTO `roomdetail` VALUES ('119', '3 x 4.3 ตร.ม.', NULL, 'ไม่มีเฟอร์นิเจอร์ เป็นห้องเปล่า', NULL, '2,000 บาท', '102');",
"INSERT INTO `roomdetail` VALUES ('12', '20 ตร.ม.', 'แอร์', 'เตียง,ฟูก,ตู้เสื้อผ้า,โต๊ะ,มีชั้นวาง,โต๊ะคอม,เก้าอี้มี 2 ชุด,มีทีวี LCD 32 นิ้ว', 'อยู่ได้ 2 คน,ห้องที่อยู่ริมทุกห้องเสียเพิ่ม 500 บาท', '4,900 บาท', '1');",
"INSERT INTO `roomdetail` VALUES ('120', '3.3x 4.5 ตร.ม.', NULL, 'โต๊ะคอม ตู้เสื้อผ้า', NULL, '2,300 บาท', '102');",
"INSERT INTO `roomdetail` VALUES ('121', '3 x 7.5 ตร.ม.', NULL, 'เตียง ฟูก ระเบียง ตู้ โต๊ะญี่ปุ่น ตู้เสื้อผ้า', NULL, '2,700 บาท', '103');",
"INSERT INTO `roomdetail` VALUES ('122', '3.5 x 8 ตร.ม.', NULL, 'เตียง ฟูก ระเบียง ตู้ โต๊ะญี่ปุ่น ตู้เสื้อผ้า', NULL, '3,000 บาท', '103');",
"INSERT INTO `roomdetail` VALUES ('123', NULL, 'พัดลม', 'เตียง,ฟูก,ตู้เสื้อผ้า,โต๊ะ,พัดลม', NULL, '3,400 บาท', '96');",
"INSERT INTO `roomdetail` VALUES ('124', NULL, 'แอร์', 'เตียง,ฟูก,ตู้เสื้อผ้า,โต๊ะ,พัดลม', NULL, '4,200 บาท', '96');",
"INSERT INTO `roomdetail` VALUES ('125', '3 x 4 ตร.ม.', 'พัดลม', 'ตู้ โต๊ะ พัดลม', NULL, '2,300 บาท', '105');",
"INSERT INTO `roomdetail` VALUES ('126', NULL, 'แอร์', 'เตียง,ฟูก,ตู้เสื้อผ้า,โต๊ะ 2 ตัว,เก้าอี้มี 2 ชุด', NULL, '4,260 บาท', '106');",
"INSERT INTO `roomdetail` VALUES ('127', NULL, 'แอร์', 'เตียง,ฟูก,ตู้เสื้อผ้า,โต๊ะ 2 ตัว,เก้าอี้มี 2 ชุด,เครื่องทำน้ำอุ่น', NULL, '4,460 บาท', '106');",
"INSERT INTO `roomdetail` VALUES ('128', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '2,700 บาท', '104');",
"INSERT INTO `roomdetail` VALUES ('129', NULL, 'แอร์', 'เตียง,ฟูก,ตู้เสื้อผ้า,โต๊ะ 2 ตัว,เก้าอี้มี 2 ชุด,เครื่องทำน้ำอุ่น', NULL, '5,000 บาท', '106');",
"INSERT INTO `roomdetail` VALUES ('13', '20 ตร.ม.', 'แอร์', 'เตียง,ฟูก,ตู้เสื้อผ้า,โต๊ะ,มีชั้นวาง,โต๊ะคอม,เก้าอี้มี 2 ชุด', 'อยู่ได้ 2 คน,ตามชั้น,ห้องที่อยู่ริมทุกห้องเสียเพิ่ม 500 บาท', '5,000 บาท', '1');",
"INSERT INTO `roomdetail` VALUES ('130', '4 x 7.5 ตร.ม.', 'แอร์', 'เตียง ฟูก พัดลม ระเบียง โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น', NULL, '4,700 บาท', '108');",
"INSERT INTO `roomdetail` VALUES ('131', '4 x 6.5 ตร.ม.', 'แอร์', 'เตียง ฟูก พัดลม ระเบียง โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น', NULL, '4,500 บาท', '108');",
"INSERT INTO `roomdetail` VALUES ('132', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '2,500 บาท', '109');",
"INSERT INTO `roomdetail` VALUES ('133', NULL, 'แอร์', 'เตียง ฟูก โต๊ะ ตู้เสื้อผ้า', NULL, '3,500 บาท', '110');",
"INSERT INTO `roomdetail` VALUES ('134', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', 'ตึกหญิง', '2,800 บาท', '110');",
"INSERT INTO `roomdetail` VALUES ('135', NULL, 'พัดลม', 'พัดลม โต๊ะ ตู้', 'ตึกชาย', '2,500 บาท', '110');",
"INSERT INTO `roomdetail` VALUES ('136', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '2,200 บาท', '111');",
"INSERT INTO `roomdetail` VALUES ('137', NULL, 'พัดลม', 'พัดลม โต๊ะ ตู้', NULL, '2,500 บาท', '112');",
"INSERT INTO `roomdetail` VALUES ('138', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,300 บาท', '113');",
"INSERT INTO `roomdetail` VALUES ('139', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', 'ชั้นบนสุด', '3,100 บาท', '113');",
"INSERT INTO `roomdetail` VALUES ('14', '30 ตร.ม.', 'แอร์', 'มีพัดลม,ตู้เย็น,ตู้เสื้อผ้า,เตียงนอน,ทีวี', 'อยู่ชั้น 4 ถ้าอยู่ห้องมุมเสียเพิ่ม 500 บาท', '4,000 บาท', '2');",
"INSERT INTO `roomdetail` VALUES ('140', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '2,900 บาท', '114');",
"INSERT INTO `roomdetail` VALUES ('141', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,600 บาท', '114');",
"INSERT INTO `roomdetail` VALUES ('142', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,200 บาท', '115');",
"INSERT INTO `roomdetail` VALUES ('143', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '4,200 บาท', '115');",
"INSERT INTO `roomdetail` VALUES ('144', NULL, 'พัดลม', 'ตู้ พัดลม', NULL, '2,000 บาท', '116');",
"INSERT INTO `roomdetail` VALUES ('145', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '2,800 บาท', '117');",
"INSERT INTO `roomdetail` VALUES ('146', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,000 บาท', '100');",
"INSERT INTO `roomdetail` VALUES ('147', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,000 บาท', '118');",
"INSERT INTO `roomdetail` VALUES ('148', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,800 บาท', '118');",
"INSERT INTO `roomdetail` VALUES ('149', NULL, 'แอร์', 'เตียง ฟูก โต๊ะ ตู้เสื้อผ้า', NULL, '4,000 บาท', '119');",
"INSERT INTO `roomdetail` VALUES ('15', '30 ตร.ม.', 'แอร์', 'มีพัดลม,ตู้เย็น,ตู้เสื้อผ้า,เตียงนอน,ทีวี', 'อยู่ชั้น 3 ถ้าอยู่ห้องมุมเสียเพิ่ม 500 บาท', '4,500 บาท', '2');",
"INSERT INTO `roomdetail` VALUES ('150', NULL, 'แอร์', 'เตียง ฟูก โต๊ะ ตู้เสื้อผ้า', NULL, '4,200 บาท', '119');",
"INSERT INTO `roomdetail` VALUES ('151', NULL, 'พัดลม', 'เตียง ฟูก ระเบียง โต๊ะคอม ตู้เสื้อผ้า พัดลม', NULL, '3,000 บาท', '90');",
"INSERT INTO `roomdetail` VALUES ('152', '4 x 6.5 ตร.ม.', 'พัดลม', 'เตียง ฟูก โต๊ะ ตู้เสื้อผ้า', NULL, '3,500 บาท', '120');",
"INSERT INTO `roomdetail` VALUES ('153', '4 x 6.5 ตร.ม.', 'แอร์', 'เตียง ฟูก โต๊ะ ตู้เสื้อผ้า', NULL, '4,200 บาท', '120');",
"INSERT INTO `roomdetail` VALUES ('154', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,000 บาท', '121');",
"INSERT INTO `roomdetail` VALUES ('155', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '4,000 บาท', '121');",
"INSERT INTO `roomdetail` VALUES ('156', NULL, 'พัดลม', 'เตียง ฟูก พัดลม ตู้เสื้อผ้า', NULL, '3,000 บาทขึ้นไป', '122');",
"INSERT INTO `roomdetail` VALUES ('157', NULL, 'แอร์', 'เตียง ฟูก ตู้เสื้อผ้า', NULL, '4,400 บาท', '122');",
"INSERT INTO `roomdetail` VALUES ('158', NULL, NULL, 'เตียง ฟูก โต๊ะ ตู้เสื้อผ้า', NULL, '2,800บาท', '123');",
"INSERT INTO `roomdetail` VALUES ('159', NULL, 'แอร์', 'เตียง ฟูก โต๊ะ ตู้เสื้อผ้า', NULL, '3,500 บาท', '123');",
"INSERT INTO `roomdetail` VALUES ('16', '30 ตร.ม.', 'แอร์', 'มีพัดลม,ตู้เย็น,ตู้เสื้อผ้า,เตียงนอน,ทีวี,เครื่องเล่นดีวีดี,ไมโครเวฟ', 'อยู่ชั้น 1-2', '5,000 บาท', '2');",
"INSERT INTO `roomdetail` VALUES ('160', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,000 บาท', '124');",
"INSERT INTO `roomdetail` VALUES ('161', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,800 บาท', '124');",
"INSERT INTO `roomdetail` VALUES ('162', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,500 บาท', '125');",
"INSERT INTO `roomdetail` VALUES ('163', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น ทีวี', NULL, '4,300 บาท', '125');",
"INSERT INTO `roomdetail` VALUES ('164', NULL, 'พัดลม', 'เตียง ฟูก ระเบียง พัดลม', NULL, '3,000 บาท', '126');",
"INSERT INTO `roomdetail` VALUES ('165', NULL, 'พัดลม', 'เตียง ฟูก พัดลม ระเบียง', NULL, '3,200 บาท', '126');",
"INSERT INTO `roomdetail` VALUES ('166', NULL, 'แอร์', 'เตียง ฟูก ระเบียง พัดลม', NULL, '3,800 บาท', '126');",
"INSERT INTO `roomdetail` VALUES ('167', NULL, 'แอร์', 'เตียง ฟูก โต๊ะ ตู้เสื้อผ้า', NULL, '4,300 บาท', '127');",
"INSERT INTO `roomdetail` VALUES ('168', NULL, 'พัดลม', 'เตียง ฟูก โต๊ะ ตู้เสื้อผ้า', NULL, '2,900 บาท', '128');",
"INSERT INTO `roomdetail` VALUES ('169', NULL, 'แอร์', 'เตียง ฟูก โต๊ะ ตู้เสื้อผ้า', NULL, '3,500 บาท', '128');",
"INSERT INTO `roomdetail` VALUES ('17', '', 'พัดลม', 'เตียง,ตู้เสื้อผ้า,พัดลม', NULL, '3,500 บาท', '3');",
"INSERT INTO `roomdetail` VALUES ('170', NULL, 'แอร์', 'เตียง ฟูก โต๊ะ ตู้เสื้อผ้า', NULL, '3,600 บาท', '129');",
"INSERT INTO `roomdetail` VALUES ('171', NULL, 'แอร์', 'เตียง ฟูก โต๊ะ ตู้เสื้อผ้า', NULL, '4,500 บาท', '130');",
"INSERT INTO `roomdetail` VALUES ('172', NULL, 'พัดลม', 'พัดลม ตู้ โต๊ะ', NULL, '2,200 บาท', '131');",
"INSERT INTO `roomdetail` VALUES ('173', NULL, 'แอร์', 'เตียงนอน,ตู้เสื้อผ้า,เครื่องทำน้ำอุ่น,ทีวี,ฟูก,โต๊ะ', NULL, '5,000 บาท', '132');",
"INSERT INTO `roomdetail` VALUES ('174', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,500 บาท', '133');",
"INSERT INTO `roomdetail` VALUES ('175', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,800 บาท', '133');",
"INSERT INTO `roomdetail` VALUES ('176', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '4,500 บาท', '133');",
"INSERT INTO `roomdetail` VALUES ('177', NULL, 'พัดลม', 'ตู้ โต๊ะ พัดลม', NULL, '2,000 บาท', '41');",
"INSERT INTO `roomdetail` VALUES ('178', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,000 บาท', '41');",
"INSERT INTO `roomdetail` VALUES ('179', NULL, NULL, 'เตียง ฟูก พัดลม ตู้', NULL, '2,300-3,000 บาท', '42');",
"INSERT INTO `roomdetail` VALUES ('18', NULL, 'แอร์', 'เตียง พัดลม ตู้เสื้อผ้า เครื่องทำน้ำอุ่น', NULL, '4,000 บาท', '3');",
"INSERT INTO `roomdetail` VALUES ('180', '3.5 x 5.5', 'พัดลม', 'เตียง ฟูก  โต๊ะ ตู้เสื้อผ้า', NULL, '2,600 บาท', '43');",
"INSERT INTO `roomdetail` VALUES ('181', '3.5 x 5.5', 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,500 บาท', '43');",
"INSERT INTO `roomdetail` VALUES ('182', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '2,600 บาท', '45');",
"INSERT INTO `roomdetail` VALUES ('183', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,500 บาท', '45');",
"INSERT INTO `roomdetail` VALUES ('184', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '2,500 บาท', '46');",
"INSERT INTO `roomdetail` VALUES ('185', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า ตู้เย็น', NULL, '3,000 บาท', '46');",
"INSERT INTO `roomdetail` VALUES ('186', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า ตู้เย็น', NULL, '3,500 บาท', '46');",
"INSERT INTO `roomdetail` VALUES ('187', NULL, NULL, 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '2,500 บาท', '47');",
"INSERT INTO `roomdetail` VALUES ('188', NULL, NULL, 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '2,900 บาท', '47');",
"INSERT INTO `roomdetail` VALUES ('189', NULL, 'พัดลม', 'เตียง ฟูก พัดลม ตู้เสื้อผ้า', NULL, '2,100 บาท', '49');",
"INSERT INTO `roomdetail` VALUES ('19', NULL, 'แอร์', 'เตียง ฟูก ตู้เย็น ทีวี พัดลม เครื่องทำน้ำอุ่น', NULL, '4,500 บาท', '3');",
"INSERT INTO `roomdetail` VALUES ('190', NULL, 'พัดลม', 'เตียง ฟูก พัดลม ตู้เสื้อผ้า', NULL, '2,300 บาท', '49');",
"INSERT INTO `roomdetail` VALUES ('191', NULL, 'แอร์', 'เตียง ฟูก ตู้เสื้อผ้า', NULL, '2,700 บาท', '49');",
"INSERT INTO `roomdetail` VALUES ('192', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '2,600 บาท', '50');",
"INSERT INTO `roomdetail` VALUES ('193', NULL, 'พัดลม', 'เตียง ฟูก โต๊ะ ตู้เสื้อผ้า ตู้เย็น', NULL, '2,500 บาท', '51');",
"INSERT INTO `roomdetail` VALUES ('194', NULL, 'พัดลม', 'เตียง ฟูก  โต๊ะ ตู้เสื้อผ้า ตู้เย็น', NULL, '2,700 บาท', '51');",
"INSERT INTO `roomdetail` VALUES ('195', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า ตู้เย็น', NULL, '3,000 บาท', '51');",
"INSERT INTO `roomdetail` VALUES ('196', NULL, 'พัดลม', 'เตียง ฟูก  โต๊ะ ตู้เสื้อผ้า', NULL, '3,400 บาท', '52');",
"INSERT INTO `roomdetail` VALUES ('197', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,600 บาท', '52');",
"INSERT INTO `roomdetail` VALUES ('198', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น', NULL, '4,400 บาท', '52');",
"INSERT INTO `roomdetail` VALUES ('199', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น', NULL, '4,200 บาท', '52');",
"INSERT INTO `roomdetail` VALUES ('2', NULL, 'แอร์', NULL, NULL, '3,000 บาท', '40');",
"INSERT INTO `roomdetail` VALUES ('20', NULL, 'แอร์', 'เตียง ฟูก ตู้เย็น ทีวี พัดลม เครื่องทำน้ำอุ่น', 'เป็นห้องสูท มีแอร์ตัวเดียว', '7,000 บาท', '3');",
"INSERT INTO `roomdetail` VALUES ('200', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น', NULL, '3,100 บาท', '53');",
"INSERT INTO `roomdetail` VALUES ('201', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น', NULL, '3,300 บาท', '53');",
"INSERT INTO `roomdetail` VALUES ('202', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น', NULL, '3,900 บาท', '53');",
"INSERT INTO `roomdetail` VALUES ('203', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น', NULL, '4,100 บาท', '53');",
"INSERT INTO `roomdetail` VALUES ('204', NULL, 'พัดลม', 'เตียง ฟูก โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น', NULL, '3,600 บาท', '54');",
"INSERT INTO `roomdetail` VALUES ('205', NULL, 'แอร์', 'เตียง ฟูก โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น', NULL, '4,300 บาท', '54');",
"INSERT INTO `roomdetail` VALUES ('206', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น', NULL, '3,500 บาท', '55');",
"INSERT INTO `roomdetail` VALUES ('207', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น', NULL, '4,300 บาท', '55');",
"INSERT INTO `roomdetail` VALUES ('208', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,000 บาท', '57');",
"INSERT INTO `roomdetail` VALUES ('209', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น', NULL, '3,800 บาท', '57');",
"INSERT INTO `roomdetail` VALUES ('21', NULL, 'แอร์', 'เตียง ฟูก ตู้เย็น ทีวี พัดลม เครื่องทำน้ำอุ่น', 'ห้องสูทห้องใหญ่', '8,000 บาท', '3');",
"INSERT INTO `roomdetail` VALUES ('210', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '2,800 บาท', '58');",
"INSERT INTO `roomdetail` VALUES ('211', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,500 บาท', '58');",
"INSERT INTO `roomdetail` VALUES ('212', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '2,700 บาท', '59');",
"INSERT INTO `roomdetail` VALUES ('213', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,500 บาท', '59');",
"INSERT INTO `roomdetail` VALUES ('214', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,000 บาท', '61');",
"INSERT INTO `roomdetail` VALUES ('215', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '4,000 บาท', '61');",
"INSERT INTO `roomdetail` VALUES ('216', '3.5 x 5.5', 'พัดลม', 'เตียง ฟูก โต๊ะ ตู้เสื้อผ้า', 'มีระเบียง', '2,600 บาท', '62');",
"INSERT INTO `roomdetail` VALUES ('217', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,200 บาท', '62');",
"INSERT INTO `roomdetail` VALUES ('218', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,800 บาท', '62');",
"INSERT INTO `roomdetail` VALUES ('219', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '2,500 บาท', '63');",
"INSERT INTO `roomdetail` VALUES ('22', NULL, NULL, 'เตียงนอน,ตู้เสื้อผ้า,พัดลม,โต๊ะเครื่องแป้ง,โต๊ะอ่านหนังสือ,โต๊ะทานอาหาร', NULL, '4,000 บาท', '6');",
"INSERT INTO `roomdetail` VALUES ('220', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,200 บาท', '63');",
"INSERT INTO `roomdetail` VALUES ('221', NULL, 'พัดลม', 'เตียง ฟูก เครื่องทำน้ำอุ่น โต๊ะ ตู้เสื้อผ้า', NULL, '3,800 บาท', '64');",
"INSERT INTO `roomdetail` VALUES ('222', NULL, 'แอร์', 'เตียง ฟูก โต๊ะ ตู้เสื้อผ้า', NULL, '4,800 บาท', '64');",
"INSERT INTO `roomdetail` VALUES ('223', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น', NULL, '3,500 บาท', '65');",
"INSERT INTO `roomdetail` VALUES ('224', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น', NULL, '4,500 บาท', '65');",
"INSERT INTO `roomdetail` VALUES ('225', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '3,500 บาท', '66');",
"INSERT INTO `roomdetail` VALUES ('226', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้เสื้อผ้า', NULL, '4,200 บาท', '66');",
"INSERT INTO `roomdetail` VALUES ('227', NULL, NULL, 'พัดลมเพดาน โต๊ะ ตู้', NULL, '2,800 บาท', '34');",
"INSERT INTO `roomdetail` VALUES ('228', NULL, 'แอร์', 'เตียง ที่นอน โต๊ะ ตู้', NULL, '', '31');",
"INSERT INTO `roomdetail` VALUES ('229', NULL, NULL, 'เตียง พัดลม โต๊ะ ตู้', NULL, '2,500-4,000 บาท', '138');",
"INSERT INTO `roomdetail` VALUES ('23', NULL, NULL, 'เตียงนอน,ตู้เสื้อผ้า ทีวี ตู้วางทีวี โทรศัพท์ เครื่องทำน้ำอุ่น ผ้าปูที่นอน', NULL, '5,000 บาท', '6');",
"INSERT INTO `roomdetail` VALUES ('230', NULL, NULL, 'เตียง ที่นอน พัดลม โต๊ะ ตู้', NULL, '3,200-4,200 บาท', '139');",
"INSERT INTO `roomdetail` VALUES ('231', NULL, NULL, 'เตียง ที่นอน ตู้ โต๊ะ', NULL, '3,500-4,500 บาท', '140');",
"INSERT INTO `roomdetail` VALUES ('232', NULL, 'พัดลม', 'พัดลมเพดาน', NULL, '2,300 บาท', '141');",
"INSERT INTO `roomdetail` VALUES ('233', NULL, NULL, NULL, NULL, '2,000-3,500 บาท', '142');",
"INSERT INTO `roomdetail` VALUES ('234', NULL, NULL, 'เตียง ที่นอน พัดลม โต๊ะ ตู้', NULL, '2,000-3,000 บาท', '143');",
"INSERT INTO `roomdetail` VALUES ('235', '3.5 x 4', 'แอร์', 'ตู้ เตียง โต๊ะ เครื่องทำน้ำอุ่น', NULL, '3,700 และ 4,200 บาท(3คน)', '144');",
"INSERT INTO `roomdetail` VALUES ('236', NULL, 'แอร์', 'ทีวี ตู้เย็น เครื่องทำน้ำอุ่น ชั้นวาง ไมโครเวฟ  ตู้เสื้อผ้า', '', '3,000-7,000 บาท', '145');",
"INSERT INTO `roomdetail` VALUES ('237', '3.5 x 5.5', 'แอร์ / พัดลม', 'โต๊ะคอม ตู้เสื้อผ้า เตียงคู่', 'มีระเบียง', 'พัดลม 2,500 บาท\r\nแอร์ 3,000 บาท', '146');",
"INSERT INTO `roomdetail` VALUES ('238', '4 x 5.5', 'แอร์ / พัดลม', 'โต๊ะ เก้าอี้ ตู้เสื้อผ้า เตียงคู่', 'มีระเบียง', 'ห้องพัดลม 2,800 บาท\r\nห้องแอร์    3,500 บาท', '147');",
"INSERT INTO `roomdetail` VALUES ('239', '4 x 8 ตร.ม.', 'พัดลม', 'เตียง 6 ฟุต ฟูก ตู้ โต๊ะ เก้าอี้', 'มีระเบียง', '3,000 บาท', '148');",
"INSERT INTO `roomdetail` VALUES ('24', '24 ตร.ม.', 'แอร์', 'เตียง ตู้เย็น ทีวี โต๊ะเครื่องแป้ง โต๊ะคอม เครื่องทำน้ำอุ่น', 'อยู่ได้ 2-3 คน', '4,000 บาท', '8');",
"INSERT INTO `roomdetail` VALUES ('240', '4 x 8 ตร.ม.', 'แอร์', 'เตียง 6 ฟุต ฟูก ตู้ โต๊ะ เก้าอี้ พัดลม', 'มีระเบียง', '4,300 บาท', '148');",
"INSERT INTO `roomdetail` VALUES ('241', NULL, 'แอร์', 'เตียง 6 ฟุต ฟูก ตู้ โต๊ะ เก้าอี้ พัดลม', '1 ห้องน้ำ 2 ห้องนอน 1 ห้องโถง(บ้าน)', '6,000 บาท', '148');",
"INSERT INTO `roomdetail` VALUES ('242', '4 x 6', 'แอร์', 'โต๊ะ ตู้ เตียง เก้าอี้ พัดลม', 'มีระเบียง', '3,700 บาท', '149');",
"INSERT INTO `roomdetail` VALUES ('243', NULL, NULL, 'มีโต๊ะ ตู้ เตียง เก้าอี้ ที่นอน', NULL, 'ประมาณ 3,000-3,800 บาท', '150');",
"INSERT INTO `roomdetail` VALUES ('244', 'เล็ก', 'พัดลม', 'โต๊ะ ตู้ เตียง ', NULL, '2,200 บาท', '151');",
"INSERT INTO `roomdetail` VALUES ('245', NULL, NULL, 'มีตู้ โต๊ะ โทรศัพท์', NULL, 'ประมาณ 2,000-2,400 บาท', '152');",
"INSERT INTO `roomdetail` VALUES ('246', NULL, NULL, 'มีเตียง โต๊ะ ตู้', NULL, 'ประมาณ 3,000 บาท', '153');",
"INSERT INTO `roomdetail` VALUES ('247', NULL, 'แอร์', 'มีเตียง', NULL, 'ประมาณ 3,500 บาท', '153');",
"INSERT INTO `roomdetail` VALUES ('248', NULL, 'พัดลม', 'เตียง ฟูก ตู้ โต๊ะ ', NULL, '2,600 บาท', '155');",
"INSERT INTO `roomdetail` VALUES ('249', NULL, 'แอร์', 'เตียง ฟูก ตู้ โต๊ะ ', NULL, '3,100 บาท', '155');",
"INSERT INTO `roomdetail` VALUES ('25', '48 ตร.ม.', 'แอร์', 'เตียง ตู้เย็น ทีวี โต๊ะเครื่องแป้ง โต๊ะคอม เครื่องทำน้ำอุ่น', 'อยู่ได้ 4-5 คน', '8,000 บาท', '8');",
"INSERT INTO `roomdetail` VALUES ('250', NULL, 'พัดลม', 'มีเตียง ฟูก ตู้ไม้ เก้าอี้', NULL, 'ประมาณ 2,800 บาท', '156');",
"INSERT INTO `roomdetail` VALUES ('251', NULL, 'พัดลม', 'มีเตียง ฟูก ตู้ไม้ เก้าอี้', NULL, 'ประมาณ 3,000 บาท', '156');",
"INSERT INTO `roomdetail` VALUES ('252', NULL, 'แอร์', 'มีเตียง ฟูก ตู้ไม้ เก้าอี้', NULL, 'ประมาณ 3,500 บาท', '156');",
"INSERT INTO `roomdetail` VALUES ('253', NULL, 'พัดลม', 'มีเตียง ฟูก ตู้ไม้ เก้าอี้', NULL, 'ประมาณ 2,800 บาท', '157');",
"INSERT INTO `roomdetail` VALUES ('254', NULL, 'พัดลม', 'มีเตียง ฟูก ตู้ไม้ เก้าอี้', NULL, 'ประมาณ 3,000 บาท', '157');",
"INSERT INTO `roomdetail` VALUES ('255', NULL, 'แอร์', 'มีเตียง ฟูก ตู้ไม้ เก้าอี้', NULL, 'ประมาณ 3,500 บาท', '157');",
"INSERT INTO `roomdetail` VALUES ('256', '3 x 4', 'พัดลม', 'มีพัดลม ตู้ เก้าอี้ โต๊ะ เตียง ฟูก', 'มีระเบียง', '2,500 บาท', '158');",
"INSERT INTO `roomdetail` VALUES ('257', '3 x 4', 'แอร์', 'ตู้ เก้าอี้ โต๊ะ เตียง ฟูก พัดลม', 'มีระเบียง', '3,000 บาท', '158');",
"INSERT INTO `roomdetail` VALUES ('258', NULL, 'ธรรมดา', 'มีตู้ โต๊ะ เตียง ฟูก', NULL, 'ประมาณ 2,300 บาท', '159');",
"INSERT INTO `roomdetail` VALUES ('259', NULL, 'แอร์', 'มีตู้ โต๊ะ เตียง ฟูก', NULL, 'ประมาณ 3,000 บาท', '159');",
"INSERT INTO `roomdetail` VALUES ('26', '20 ตร.ม.', NULL, 'เตียง,ตู้เสื้อผ้า,ทีวี,ตู้เย็น', 'อยู่ได้ 2 คน', '4,100 บาท', '9');",
"INSERT INTO `roomdetail` VALUES ('260', NULL, 'พัดลม', 'ตู้ โต๊ะ เตียง ฟูก เครื่องทำน้ำอุ่น', '', 'ประมาณ 3,000 บาท', '160');",
"INSERT INTO `roomdetail` VALUES ('261', NULL, 'แอร์', 'มีตู้ โต๊ะ เตียง ฟูก เครื่องทำน้ำอุ่น', NULL, 'ประมาณ 3,500 บาท', '160');",
"INSERT INTO `roomdetail` VALUES ('262', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ', NULL, '2,700 บาท', '77');",
"INSERT INTO `roomdetail` VALUES ('263', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ', NULL, '3,600 บาท', '77');",
"INSERT INTO `roomdetail` VALUES ('264', NULL, 'พัดลม', 'เตียง ฟูก พัดลม โต๊ะ ตู้', NULL, '3,000 บาท', '39');",
"INSERT INTO `roomdetail` VALUES ('265', NULL, 'แอร์', 'เตียง ฟูก พัดลม โต๊ะ ตู้', NULL, '3,500 บาท', '39');",
"INSERT INTO `roomdetail` VALUES ('266', NULL, 'พัดลม', 'ตู้ โต๊ะ เตียง ที่นอน พัดลม', NULL, '2,700 บาท', '72');",
"INSERT INTO `roomdetail` VALUES ('267', NULL, NULL, 'เตียง ฟูก โต๊ะ ตู้ ชั้นวางของ', NULL, '3,800-4,300 บาท', '74');",
"INSERT INTO `roomdetail` VALUES ('268', NULL, 'พัดลม', 'เตียง,ฟูก,ตู้,โต๊ะ,เก้าอี้', NULL, '2,000-2,500 บาท', '78');",
"INSERT INTO `roomdetail` VALUES ('269', NULL, 'พัดลม', 'ตู้ โต๊ะ เตียง พัดลม ', NULL, '3,000 บาท', '79');",
"INSERT INTO `roomdetail` VALUES ('27', '4x4 ตร.ม.', 'แอร์', 'ตู้เสื้อผ้า โต๊ะ เตียง ', 'ไม่จำกัดคนอยู่', '3,700 บาท', '10');",
"INSERT INTO `roomdetail` VALUES ('270', NULL, 'แอร์', 'ตู้ โต๊ะ เตียง', NULL, '3,500 บาท', '79');",
"INSERT INTO `roomdetail` VALUES ('271', NULL, 'พัดลม', 'เตียง,ตู้,โต๊ะ,เครื่องทำน้ำอุ่น,เก้าอี้', NULL, '3,000 บาท', '162');",
"INSERT INTO `roomdetail` VALUES ('272', NULL, 'แอร์', 'เตียง,ตู้,โต๊ะ,เครื่องทำน้ำอุ่น,เก้าอี้', NULL, '3,500 บาท', '162');",
"INSERT INTO `roomdetail` VALUES ('273', NULL, NULL, 'เตียง,ฟูก,ตู้,โต๊ะ,พัดลม', NULL, '2,300 บาท', '164');",
"INSERT INTO `roomdetail` VALUES ('274', NULL, NULL, 'เตียง,ฟูก,ตู้,โต๊ะ,พัดลม', NULL, '3,400 บาท', '165');",
"INSERT INTO `roomdetail` VALUES ('275', NULL, NULL, 'เตียง,ตู้,โต๊ะ,โต๊ะเครื่องแป้ง', NULL, '', '166');",
"INSERT INTO `roomdetail` VALUES ('276', NULL, 'แอร์', 'เตียง,ตู้,โต๊ะ,ฟูก,พัดลม', 'นักศึกษา', '3,300 บาท', '167');",
"INSERT INTO `roomdetail` VALUES ('277', NULL, 'แอร์', 'เตียง,ตู้,โต๊ะ,ฟูก,พัดลม', 'คนทำงาน', '3,500 บาท', '167');",
"INSERT INTO `roomdetail` VALUES ('278', NULL, 'แอร์', 'เตียง,ตู้,โต๊ะ,ฟูก,พัดลม', NULL, '3,500 บาท', '168');",
"INSERT INTO `roomdetail` VALUES ('279', NULL, NULL, 'เตียง,ตู้,โต๊ะ,ฟูก,พัดลม,หมอน,เก้าอี้', NULL, '2,700 บาท', '169');",
"INSERT INTO `roomdetail` VALUES ('28', '4x4 ตร.ม.', 'แอร์', 'ตู้เสื้อผ้า โต๊ะ เตียง ทีวี ตู้เย็น', 'ไม่จำกัดคนอยู่', '4,500 บาท', '10');",
"INSERT INTO `roomdetail` VALUES ('280', NULL, 'พัดลม', 'เตียง,ตู้,โต๊ะ,พัดลม', NULL, '2,400 บาท', '170');",
"INSERT INTO `roomdetail` VALUES ('281', NULL, 'พัดลม', 'เตียง,ตู้,โต๊ะ,ฟูก,พัดลม', NULL, '2,700 บาท', '171');",
"INSERT INTO `roomdetail` VALUES ('282', NULL, 'แอร์', 'เตียง,ตู้,โต๊ะ,ฟูก', NULL, '3,700 บาท', '171');",
"INSERT INTO `roomdetail` VALUES ('283', NULL, 'แอร์', 'เตียง,ตู้,โต๊ะ,เครื่องทำน้ำอุ่น,ฟูก', 'ติด UBC เพิ่ม 100 บาท', '3,800 บาท', '172');",
"INSERT INTO `roomdetail` VALUES ('284', NULL, 'แอร์', 'เตียง,ตู้,โต๊ะ,เครื่องทำน้ำอุ่น,ฟูก', 'ห้องมุม ติดUBC เพิ่ม 100 บาท', '4,000 บาท', '172');",
"INSERT INTO `roomdetail` VALUES ('285', NULL, 'พัดลม', 'พัดลม ตู้ โต๊ะ', NULL, '2,000 บาท', '173');",
"INSERT INTO `roomdetail` VALUES ('286', NULL, 'พัดลม', 'เตียง,ตู้,โต๊ะ,พัดลมเพดาน', NULL, '2,500 บาท', '174');",
"INSERT INTO `roomdetail` VALUES ('288', NULL, 'แอร์', 'เตียง,ตู้,โต๊ะ,ฟูก,พัดลม', NULL, '2,900 บาท', '175');",
"INSERT INTO `roomdetail` VALUES ('289', NULL, 'พัดลม', 'เตียง,ตู้,โต๊ะ,ฟูก', NULL, '', '176');",
"INSERT INTO `roomdetail` VALUES ('29', '6x4 ตร.ม.', NULL, NULL, NULL, '7,000 บาท', '10');",
"INSERT INTO `roomdetail` VALUES ('290', NULL, 'แอร์', 'เตียง,ตู้,โต๊ะ,ฟูก', NULL, '', '176');",
"INSERT INTO `roomdetail` VALUES ('293', NULL, NULL, 'พัดลม โต๊ะ', NULL, '1,800 บาท', '178');",
"INSERT INTO `roomdetail` VALUES ('294', NULL, NULL, 'ตู้,โต๊ะ,พัดลม', NULL, '2,200 บาท', '179');",
"INSERT INTO `roomdetail` VALUES ('295', NULL, 'แอร์', 'เตียง,ตู้,โต๊ะ,ฟูก,โต๊ะเครื่องแป้ง', NULL, '3,100 บาท', '180');",
"INSERT INTO `roomdetail` VALUES ('297', NULL, 'แอร์', 'เตียง,ตู้,โต๊ะ', NULL, '3,000 บาท', '174');",
"INSERT INTO `roomdetail` VALUES ('3', '24 ตร.ม.', 'แอร์', NULL, NULL, '4,200 บาท', '52');",
"INSERT INTO `roomdetail` VALUES ('30', '26 ตร.ม.', 'แอร์', 'เตียงนอน,ตู้เสื้อผ้า,ชั้นวางทีวี,โต๊ะทำงาน,โต๊ะเครื่องแป้ง,', 'ทีวี ตู้เย็นมีให้เช่า', '4,200 บาท', '13');",
"INSERT INTO `roomdetail` VALUES ('31', '26 ตร.ม.', 'แอร์', 'เตียงนอน,ตู้เสื้อผ้า,ชั้นวางทีวี,โต๊ะทำงาน,โต๊ะเครื่องแป้ง,', 'ทีวี ตู้เย็นมีให้เช่า', '4,400 บาท', '13');",
"INSERT INTO `roomdetail` VALUES ('32', '26 ตร.ม.', 'พัดลม', 'เตียงนอน,ตู้เสื้อผ้า,ชั้นวางทีวี,โต๊ะทำงาน,โต๊ะเครื่องแป้ง', NULL, '3,400 บาท', '13');",
"INSERT INTO `roomdetail` VALUES ('33', '26 ตร.ม.', 'พัดลม', 'เตียงนอน,ตู้เสื้อผ้า,ชั้นวางทีวี,โต๊ะทำงาน,โต๊ะเครื่องแป้ง', NULL, '3,200 บาท', '13');",
"INSERT INTO `roomdetail` VALUES ('34', 'ใหญ่กว่า 26 ตร.ม.', 'แอร์', 'ตู้เย็น,ทีวี', 'ห้องสูท', '7,000 บาท', '13');",
"INSERT INTO `roomdetail` VALUES ('35', NULL, NULL, NULL, 'มีระเบียงด้านหลัง(กว้าง)', '5,000 บาท', '14');",
"INSERT INTO `roomdetail` VALUES ('36', NULL, NULL, NULL, 'มีระเบียงด้านหลัง(กว้าง)', '5,500 บาท', '14');",
"INSERT INTO `roomdetail` VALUES ('37', NULL, NULL, 'เฟอร์นิเจอร์พร้อม,มีทีวี 42 นิ้ว,มีไมโครเวฟ', 'มีระเบียงด้านหลัง(กว้าง),เป็นห้องสูท', '10,000 บาท', '14');",
"INSERT INTO `roomdetail` VALUES ('38', '25 ตร.ม.', 'แอร์', 'เตียงนอน,ตู้เสื้อผ้า,เครื่องทำน้ำอุ่น,ทีวี,ตู้เย็น,ไมโครเวฟ', 'อยู่ได้ 2 คน', '4,000 บาท', '15');",
"INSERT INTO `roomdetail` VALUES ('39', '25 ตร.ม.', 'แอร์', 'เตียงนอน,ตู้เสื้อผ้า,เครื่องทำน้ำอุ่น,ทีวี,ตู้เย็น,ไมโครเวฟ,โต๊ะเขียนหนังสือ,ชั้นวางรองเท้า', 'อยู่ได้ 2 คน,ติดถนน', '4,500 บาท', '15');",
"INSERT INTO `roomdetail` VALUES ('4', '21  ตร.ม.', 'แอร์', NULL, NULL, '4,000 บาท', '52');",
"INSERT INTO `roomdetail` VALUES ('40', '25 ตร.ม.', 'แอร์', 'เตียงนอน,ตู้เสื้อผ้า,เครื่องทำน้ำอุ่น,ทีวีจอแบน LCD 32 นิ้ว,ตู้เย็น,ไมโครเวฟ,โต๊ะเขียนหนังสือ,ชั้นวางรองเท้า', 'อยู่ได้ 2 คน,ริมน้ำ', '5,000 บาท', '15');",
"INSERT INTO `roomdetail` VALUES ('41', NULL, 'แอร์', 'เตียงนอน,ตู้เสื้อผ้า,เครื่องทำน้ำอุ่น,ทีวีจอแบน LCD 32 นิ้ว,ตู้เย็น,ไมโครเวฟ 2 ตัว(อยู่ส่วนกลาง),โต๊ะเขียนหนังสือ,ชั้นวางรองเท้า', 'อยู่ได้ 4 คน', '9,500 บาท', '15');",
"INSERT INTO `roomdetail` VALUES ('42', '24 ตร.ม.', 'แอร์', 'เตียงนอน,ตู้เสื้อผ้า,เครื่องทำน้ำอุ่น,ทีวี,ตู้เย็น', 'ห้องธรรมดา,อยู่ได้ไม่เกิน 3 คน', '3,500 บาท', '17');",
"INSERT INTO `roomdetail` VALUES ('43', 'มากกว่า 24 ตร.ม.', NULL, 'เตียงนอน,ตู้เสื้อผ้า,เครื่องทำน้ำอุ่น,ทีวี,ตู้เย็น', 'ห้องเชื่อม,อยู่ได้ไม่เกิน 3 คน', '', '17');",
"INSERT INTO `roomdetail` VALUES ('44', 'มากกว่า 24 ตร.ม.', 'แอร์', 'เตียงนอน,ตู้เสื้อผ้า,เครื่องทำน้ำอุ่น,ทีวี,ตู้เย็น', 'ห้องสูท,อยู่ได้ไม่เกิน 3 คน', '', '17');",
"INSERT INTO `roomdetail` VALUES ('45', 'มากกว่า 24 ตร.ม.', 'แอร์', 'เตียงนอน,ตู้เสื้อผ้า,เครื่องทำน้ำอุ่น,ทีวี,ตู้เย็น', 'ห้องมุม,อยู่ได้ไม่เกิน 3 คน', '', '17');",
"INSERT INTO `roomdetail` VALUES ('46', '4x4 ตร.ม.', 'แอร์', 'เตียงนอน,ตู้เสื้อผ้า,เครื่องทำน้ำอุ่น', 'มีตู้เย็น ทีวีให้เช่า,อยู่ได้ 2 คน', '3,700 บาท', '25');",
"INSERT INTO `roomdetail` VALUES ('47', '', 'แอร์', 'เตียงนอน,ตู้เสื้อผ้า,เครื่องทำน้ำอุ่น,ทีวี,ตู้เย็น', 'อยู่ได้ 3-4 คน', '5,500 บาท', '25');",
"INSERT INTO `roomdetail` VALUES ('48', '3.5 X 5 ตร.ม.', NULL, 'ตู้ โต๊ะ', NULL, '2,000 บาท', '70');",
"INSERT INTO `roomdetail` VALUES ('49', '3 X 5 ตร.ม.', NULL, 'เตียง ฟูก ตู้ แอร์', NULL, '3,000 บาท', '31');",
"INSERT INTO `roomdetail` VALUES ('5', '21 ตร.ม.', 'พัดลม', NULL, NULL, '3,000 บาท', '52');",
"INSERT INTO `roomdetail` VALUES ('50', '4 X6', 'แอร์', 'เตียง ฟูก ตู้ ระเบียง', NULL, '4,200', '31');",
"INSERT INTO `roomdetail` VALUES ('51', '4 x 10', 'พัดลม', 'พัดลม ระเบียง โต๊ะ ตู้', NULL, '2,800 บาท', '34');",
"INSERT INTO `roomdetail` VALUES ('52', '27-30 ตร.ม', 'พัดลม', 'ตู้ โต๊ะคอม โต๊ะวางทีวี เครื่องทำน้ำอุ่น เตียง ฟูก ระเบียง', NULL, '3,800 บาท', '32');",
"INSERT INTO `roomdetail` VALUES ('53', NULL, 'แอร์', 'ตู้ โต๊ะคอม โต๊ะวางทีวี เครื่องทำน้ำอุ่น ฟูก ระเบียง', NULL, '4,500 บาท', '32');",
"INSERT INTO `roomdetail` VALUES ('54', '4 x 3.5 ม.', 'พัดลม', 'ตู้ โต๊ะ ระเบียง', NULL, '2,500 บาท', '36');",
"INSERT INTO `roomdetail` VALUES ('55', NULL, NULL, 'เครื่องทำน้ำอุ่น ตู้ โต๊ะ โต๊ะคอม แอร์', NULL, '', '33');",
"INSERT INTO `roomdetail` VALUES ('56', NULL, NULL, 'โต๊ะ ตู้ เตียง ฟูก', NULL, '', '35');",
"INSERT INTO `roomdetail` VALUES ('57', NULL, NULL, 'เตียง ตู้ ฟูก', NULL, '2,500 บาท', '37');",
"INSERT INTO `roomdetail` VALUES ('58', NULL, NULL, 'เตียง ฟูก พัดลม ระเบียง แอร์ เครื่องทำน้ำอุ่น', NULL, '2,400 บาท', '38');",
"INSERT INTO `roomdetail` VALUES ('59', NULL, 'พัดลม', 'ตู้เสื้อผ้า  โต๊ะ 2   เก้าอี้', NULL, '3,500 บาท', '73');",
"INSERT INTO `roomdetail` VALUES ('1510', 'กลาง', 'พัดลม', 'มีระเบียง', NULL, '2,600 บาท', '151');",
"INSERT INTO `roomdetail` VALUES ('60', NULL, 'แอร์', 'ตู้เสื้อผ้า  โต๊ะ 2   เก้าอี้', NULL, '4,300 บาท', '73');",
"INSERT INTO `roomdetail` VALUES ('61', NULL, 'แอร์', 'ตู้ โต๊ะ เตียง', NULL, '3000 บาท', '75');",
"INSERT INTO `roomdetail` VALUES ('62', NULL, 'พัดลม', 'ตู้ โต๊ะ เตียง', NULL, '2500', '75');",
"INSERT INTO `roomdetail` VALUES ('63', NULL, NULL, 'ตู้ โต๊ะ เตียง', 'ริมระเบียง', '2800', '75');",
"INSERT INTO `roomdetail` VALUES ('64', NULL, 'แอร์', 'ตู้ โต๊ะ เตียง พัดลม', 'ริมระเบียง', '3200', '75');",
"INSERT INTO `roomdetail` VALUES ('65', NULL, NULL, 'ตู้ โต๊ะ เตียง', 'ริมนอก', '3200', '75');",
"INSERT INTO `roomdetail` VALUES ('66', NULL, NULL, 'ตู้ โต๊ะ เตียง', 'ริมใน', '3000', '75');",
"INSERT INTO `roomdetail` VALUES ('67', NULL, 'แอร์', 'ตู้ โต๊ะ เตียง ระเบียง พัดลม', 'ห้องกระจก', '3500', '75');",
"INSERT INTO `roomdetail` VALUES ('68', NULL, 'พัดลม', 'เตียง 5ฟุต+โต๊ะ+ตู้เสื้อผ้า', NULL, '3000', '81');",
"INSERT INTO `roomdetail` VALUES ('69', NULL, 'แอร์', 'เตียง 5ฟุต+โต๊ะ+ตู้เสื้อผ้า', NULL, '4000', '81');",
"INSERT INTO `roomdetail` VALUES ('7', '24 ตร.ม.', 'แอร์', 'โต๊ะ เตียง ฟูก ระเบียง', NULL, '4,700 บาท', '9');",
"INSERT INTO `roomdetail` VALUES ('70', NULL, 'พัดลม', 'เตียง 5ฟุต+โต๊ะ+ตู้เสื้อผ้า', NULL, '3000', '82');",
"INSERT INTO `roomdetail` VALUES ('71', NULL, 'แอร์', 'เตียง 5ฟุต+โต๊ะ+ตู้เสื้อผ้า', NULL, '4000', '82');",
"INSERT INTO `roomdetail` VALUES ('72', NULL, 'พัดลม', 'ตู้เสื้อผ้า  พัดลม', NULL, '2200 บาท', '83');",
"INSERT INTO `roomdetail` VALUES ('73', '', 'พัดลม', 'เตียง 5 ฟุต โต๊ะ ตู้เสื้อผ้า', NULL, '2800 บาท', '84');",
"INSERT INTO `roomdetail` VALUES ('74', NULL, 'พัดลม', 'เตียง 5ฟุต+โต๊ะ+ตู้เสื้อผ้า', NULL, '2500 บาท', '85');",
"INSERT INTO `roomdetail` VALUES ('75', '3.3x6 ตร.ม.', 'พัดลม', 'เตียง ฟูก พัดลม ระเบียง โต๊ะ เก้าอี้ ตู้เสื้อผ้า', NULL, '3000 บาท ', '86');",
"INSERT INTO `roomdetail` VALUES ('76', '3.3x6 ตร.ม.', 'แอร์', 'เตียง ฟูก พัดลม แอร์ ระเบียง โต๊ะ ตู้เสื้อผ้า', NULL, '3800 บาท', '86');",
"INSERT INTO `roomdetail` VALUES ('77', NULL, NULL, 'ตู้ โต๊ะ เตียง ระเบียง เก้าอี้', NULL, '', '87');",
"INSERT INTO `roomdetail` VALUES ('78', '4.2 X 3 ม.(หญิง)', 'พัดลม', 'เตียง ฟูก ระเบียง โต๊ะคอม ตู้เสื้อผ้า พัดลม', NULL, '2800 บาท', '88');",
"INSERT INTO `roomdetail` VALUES ('79', '4.2 X 3 ม.(หญิง)', 'แอร์', 'เตียง ฟูก ระเบียง โต๊ะคอม ตู้เสื้อผ้า พัดลม แอร์', NULL, '3500 บาท', '88');",
"INSERT INTO `roomdetail` VALUES ('8', '3x4 ตร.ม.', NULL, 'เตียง ฟูก ระเบียง เฟอร์นิเจอร์ เครื่องทำน้ำอุ่น', NULL, '5,000 บาท', '14');",
"INSERT INTO `roomdetail` VALUES ('80', '3.5 X 5 ม.(ชาย)', 'พัดลม', 'เตียง ฟูก ระเบียง โต๊ะคอม ตู้เสื้อผ้า พัดลม', NULL, '2800 บาท', '88');",
"INSERT INTO `roomdetail` VALUES ('81', '3.5 X 5 ม.(ชาย)', 'แอร์', 'เตียง ฟูก ระเบียง โต๊ะคอม ตู้เสื้อผ้า พัดลม แอร์', NULL, '3500 บาท', '88');",
"INSERT INTO `roomdetail` VALUES ('82', '3.2 x 4.2 ม.', 'พัดลม', 'โต๊ะคอม ตู้เสื้อผ้า เตียง ฟูก พัดลม ระเบียง', NULL, '2700 บาท', '89');",
"INSERT INTO `roomdetail` VALUES ('83', '3.2 x 4.2 ม.', 'แอร์', 'โต๊ะคอม ตู้เสื้อผ้า เตียง ฟูก พัดลม ระเบียง แอร์', NULL, '3200 บาท', '89');",
"INSERT INTO `roomdetail` VALUES ('84', '3.5 X 4.7  ม.(หอ1)', 'พัดลม', 'เตียง ฟูก ระเบียง พัดลม', NULL, '3000 บาท', '90');",
"INSERT INTO `roomdetail` VALUES ('85', '3.5 X 4.7  ม.(หอ1)', 'แอร์', 'เตียง ฟูก ระเบียง พัดลม แอร์', NULL, '3800 บาท', '90');",
"INSERT INTO `roomdetail` VALUES ('86', '3.5 X 4.7  ม.(หอ2)', 'พัดลม', 'เตียง ฟูก ระเบียง พัดลม', NULL, '3300 บาท', '90');",
"INSERT INTO `roomdetail` VALUES ('87', '3.5 X 4.7  ม.(หอ2)', 'แอร์', 'เตียง ฟูก ระเบียง พัดลม แอร์', NULL, '4200 บาท', '90');",
"INSERT INTO `roomdetail` VALUES ('88', '3 x 4 ม.', 'พัดลม', 'เตียง ฟูก พัดลม ระเบียง', NULL, '2500 บาท', '91');",
"INSERT INTO `roomdetail` VALUES ('89', '3 x 4 ม.', 'แอร์', 'เตียง ฟูก พัดลม ระเบียง แอร์', NULL, '3200 บาท', '91');",
"INSERT INTO `roomdetail` VALUES ('9', NULL, NULL, 'เตียง ฟูก ระเบียง เฟอร์นิเจอร์ เครื่องทำน้ำอุ่น', 'ห้องสูทเดี่ยว', '9,000 บาท', '14');",
"INSERT INTO `roomdetail` VALUES ('90', '3 x 6 ม.', 'แอร์', 'เตียง ฟูก พัดลม ระเบียง แอร์ ตู้เสื้อผ้า', NULL, '3800 บาท', '92');",
"INSERT INTO `roomdetail` VALUES ('91', '4 x 6 ม.', 'พัดลม', 'ตู้ใหญ่ โต๊ะ เก้าอี้ ที่นอน เตียง 6 ฟุต พัดลมเพดาน', NULL, '2500 บาท', '93');",
"INSERT INTO `roomdetail` VALUES ('92', '4 x 6 ม.', 'พัดลม', 'ตู้ใหญ่ โต๊ะ เก้าอี้ ที่นอน เตียง 6 ฟุต พัดลมเพดาน', NULL, '3000 บาท', '93');",
"INSERT INTO `roomdetail` VALUES ('93', '4 x 6 ม.', 'แอร์', 'ตู้ใหญ่ โต๊ะ เก้าอี้ ที่นอน เตียง 6 ฟุต พัดลมเพดาน แอร์', NULL, '3800  บาท', '93');",
"INSERT INTO `roomdetail` VALUES ('94', '4 X 6 ม.', 'พัดลม', 'เตียง ที่นอน 3 ฟุต(2เตียง/ห้อง)+ตู้เสื้อผ้า +พัดลม', NULL, '2800 บาท', '94');",
"INSERT INTO `roomdetail` VALUES ('95', '4 X 6 ม.', 'แอร์', 'เตียง ที่นอน 3 ฟุต(2เตียง/ห้อง)+ตู้เสื้อผ้า +พัดลม+แอร์', NULL, '3500 บาท', '94');",
"INSERT INTO `roomdetail` VALUES ('96', NULL, 'แอร์', '', 'ห้องใหญ่(ดาดฟ้า)', '4000 บาท', '94');",
"INSERT INTO `roomdetail` VALUES ('97', NULL, 'พัดลม', 'เตียง ฟูก พัดลม ระเบียง โต๊ะ ตู้เสื้อผ้า', NULL, '3,000 บาท', '86');",
"INSERT INTO `roomdetail` VALUES ('98', NULL, 'พัดลม', 'เตียง ฟูก พัดลม ระเบียง โต๊ะ ตู้เสื้อผ้า', NULL, '3,500 บาท', '86');",
"INSERT INTO `roomdetail` VALUES ('99', NULL, 'แอร์', 'เตียง ฟูก พัดลม ระเบียง โต๊ะ ตู้เสื้อผ้า เครื่องทำน้ำอุ่น', NULL, '4,000 บาท', '86');",
"INSERT INTO `roomdetail` VALUES ('1540', '3.5 x 5.5', 'พัดลม', 'ตู้ โต๊ะ เตียง  เก้าอี้', 'มีระเบียง', '2,600 บาท', '154');",
"INSERT INTO `roomdetail` VALUES ('1541', '3.5 x 5.5', 'แอร์', 'ตู้ โต๊ะ เตียง  เก้าอี้', 'มีระเบียง', '3,000 บาท', '154');",
"INSERT INTO `roomdetail` VALUES ('1542', NULL, 'แอร์', 'ตู้ โต๊ะ เตียง  เก้าอี้', 'มีระเบียง', '3,600 บาท', '154');",
"INSERT INTO `roomdetail` VALUES ('1512', 'ใหญ่', 'พัดลม', 'ตู้ โต๊ะ เตียง  เก้าอี้', NULL, '2,800 บาท', '151');",
"INSERT INTO `roomdetail` VALUES ('1513', 'ใหญ่', 'แอร์', 'ตู้ โต๊ะ เตียง  เก้าอี้', 'มีระเบียง', '3,000 บาท', '151');",
"INSERT INTO `roomdetail` VALUES ('1721', NULL, 'แอร์', 'เตียง,ตู้เสื้อผ้า,โต๊ะ,ฟูก', NULL, '3500 บาท', '172');"

);
foreach ($queries as $sql) {
	echo '<div class="container">';
	$result = mysqli_query($cn,$sql);
	if($result) {
		echo '<div class="alert alert-success" role="alert">ส่งข้อมูลเรียบร้อยแล้ว </div>';
	} else {
		echo '<div class="alert alert-danger" role="alert">ส่งข้อมูลไม่สำเร็จ</div>';
	}
	echo "</div>";
}
include("process/footer.php");
?>
